version: '3.8'

services:
  serpbear:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      CRON_TIMEZONE: ${CRON_TIMEZONE:-America/New_York}
      CRON_MAIN_SCHEDULE: "${CRON_MAIN_SCHEDULE:-0 0 0 * * *}"
      CRON_FAILED_SCHEDULE: "${CRON_FAILED_SCHEDULE:-0 0 */1 * * *}"
      CRON_EMAIL_SCHEDULE: "${CRON_EMAIL_SCHEDULE:-0 0 6 * * *}"
