name: Cleanup Caches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 03:00 UTC

jobs:
  cleanup-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GH CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install gh-actions-cache extension
        run: gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List and delete all caches (paginate)
        run: |
          echo "Deleting all caches for ${{ github.repository }}"
          while true; do
            keys=$(gh actions-cache list -R ${{ github.repository }} --limit 100 | cut -f 1)
            if [ -z "$keys" ]; then
              echo "No more caches found."
              break
            fi
            echo "$keys" | while read key; do
              if [ -n "$key" ]; then
                echo "Deleting cache: $key"
                gh actions-cache delete "$key" -R ${{ github.repository }} --confirm || true
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
